// Copyright (C) 1991-2013 Altera Corporation
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, Altera MegaCore Function License 
// Agreement, or other applicable license agreement, including, 
// without limitation, that your use is for the sole purpose of 
// programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the 
// applicable agreement for further details.


// Generated by Quartus II 64-Bit Version 13.0 (Build Build 156 04/24/2013)
// Created on Thu Jun 30 23:48:36 2016

AlarmSystem AlarmSystem_inst
(
	.CLK(CLK_sig) ,	// input  CLK_sig
	.RST(RST_sig) ,	// input  RST_sig
	.LD(LD_sig) ,	// output [9:0] LD_sig
	.Buzz(Buzz_sig) ,	// output  Buzz_sig
	.RX(RX_sig) ,	// input  RX_sig
	.TX(TX_sig) ,	// output  TX_sig
	.TXD_Bluetooth(TXD_Bluetooth_sig) ,	// input  TXD_Bluetooth_sig
	.RXD_Bluetooth(RXD_Bluetooth_sig) ,	// output  RXD_Bluetooth_sig
	.SCLK(SCLK_sig) ,	// output  SCLK_sig
	.MISO(MISO_sig) ,	// input  MISO_sig
	.MOSI(MOSI_sig) ,	// output  MOSI_sig
	.CS_ALS(CS_ALS_sig) ,	// output  CS_ALS_sig
	.CS_ACL2(CS_ACL2_sig) ,	// output  CS_ACL2_sig
	.INT_ACL2(INT_ACL2_sig) ,	// input  INT_ACL2_sig
	.Trig_US(Trig_US_sig) ,	// output  Trig_US_sig
	.Echo_US(Echo_US_sig) 	// input  Echo_US_sig
);

