// Copyright (C) 1991-2013 Altera Corporation
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, Altera MegaCore Function License 
// Agreement, or other applicable license agreement, including, 
// without limitation, that your use is for the sole purpose of 
// programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the 
// applicable agreement for further details.


// Generated by Quartus II 64-Bit Version 13.0 (Build Build 156 04/24/2013)
// Created on Sat Jul 02 10:55:08 2016

UART_WriteN UART_WriteN_inst
(
	.Clock(Clock_sig) ,	// input  Clock_sig
	.Reset(Reset_sig) ,	// input  Reset_sig
	.Buffer(Buffer_sig) ,	// input [63:0] Buffer_sig
	.Num(Num_sig) ,	// input [3:0] Num_sig
	.Trig_in(Trig_in_sig) ,	// input  Trig_in_sig
	.idle(idle_sig) ,	// output  idle_sig
	.TX(TX_sig) 	// output  TX_sig
);

